name: GrapheneOS-GSI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Sync GrapheneOS source
        run: |
          mkdir grapheneos && cd grapheneos
          repo init -u https://github.com/GrapheneOS/platform_manifest.git -b 14
          repo sync -c -j$(nproc --all) --force-sync

      - name: Apply Andy Yan’s GSI patches
        run: |
          cd grapheneos
          git clone https://github.com/AndyCGYan/lineage_build_unified -b lineage-20-light patches
          bash patches/apply.sh

      - name: Build GSI
        run: |
          cd grapheneos
          . build/envsetup.sh
          lunch aosp_arm64_ab-userdebug
          mka systemimage

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: grapheneos-gsi
          path: grapheneos/out/target/product/*/*.img
